// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkrn6YOkdjPWylHHexoK74OxtkLRm1Gmc',
    appId: '1:72043962266:web:68842ee04c90fa4a46a423',
    messagingSenderId: '72043962266',
    projectId: 'roomie-radar',
    authDomain: 'roomie-radar.firebaseapp.com',
    storageBucket: 'roomie-radar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSLtCN3f4wFRTBZMLCuU2XXPA69FG3eTw',
    appId: '1:72043962266:android:7b18c9c43ec9929646a423',
    messagingSenderId: '72043962266',
    projectId: 'roomie-radar',
    storageBucket: 'roomie-radar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnKGQAM4QhAdKi_iA3pUzMBmNlee2Y55g',
    appId: '1:72043962266:ios:d62134b8b9b25fd446a423',
    messagingSenderId: '72043962266',
    projectId: 'roomie-radar',
    storageBucket: 'roomie-radar.appspot.com',
    androidClientId: '72043962266-4dc643d9ijbambkq4sn9428i98jf3k98.apps.googleusercontent.com',
    iosClientId: '72043962266-b0q8qjr0trj7h9cqs7c8ah7echvaglbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomieRadar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnKGQAM4QhAdKi_iA3pUzMBmNlee2Y55g',
    appId: '1:72043962266:ios:d62134b8b9b25fd446a423',
    messagingSenderId: '72043962266',
    projectId: 'roomie-radar',
    storageBucket: 'roomie-radar.appspot.com',
    androidClientId: '72043962266-4dc643d9ijbambkq4sn9428i98jf3k98.apps.googleusercontent.com',
    iosClientId: '72043962266-b0q8qjr0trj7h9cqs7c8ah7echvaglbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomieRadar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkrn6YOkdjPWylHHexoK74OxtkLRm1Gmc',
    appId: '1:72043962266:web:ab5d0b1ca4d3b55d46a423',
    messagingSenderId: '72043962266',
    projectId: 'roomie-radar',
    authDomain: 'roomie-radar.firebaseapp.com',
    storageBucket: 'roomie-radar.appspot.com',
  );
}
